name: flake8 Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: upgarde pip and insall flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mccabe flake8-docstrings
      # - name: install deps
      #   run: pip install -r req.txt
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          # args: >-
          #   --max-complexity=20
          #   --max-line-length=120
          #   --exclude=__init__.py,demos,external_methods,lib/models/hific
          #   --ignore=E123,F401,D100,D101,D102,D104,D107,D401,W503
          #   --docstring-convention=numpy
          #   --args
            args: --config setup.cfg
